default: &default
  adapter: postgresql
  encoding: utf8
  host: db  # `compose.yml` の `db` に一致させる
  port: 5432
  username: root  # `docker exec` で接続できた `root` に統一
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  adapter: postgresql
  encoding: unicode
  database: papapa3_test
  username: postgres
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

